const bg1 = "../src/assets/BG1.png";
const bg2 = "../src/assets/MobView.png";
const logo = "../src/assets/PrideLogo.svg";
const menu = "../src/assets/menu.svg";
const cross = "../src/assets/close.svg";
const img1 = "../src/assets/IMG.svg";
const img2 = "../src/assets/Rating.svg";
const img3 = "../src/assets/Watch Video.svg";
const img4 = "../src/assets/Arrow.svg";
const img5 = "../src/assets/whyus1.png";
const img6 = "../src/assets/whyus2.png";
const bg3 = "../src/assets/BG.svg";
const bg4 = "../src/assets/bg3.svg";
const bg5 = "../src/assets/bg10.jpg";
const img7 = "../src/assets/design-svgrepo-com.svg"
const img8 = "../src/assets/ITSolutions.avif"
const img9 = "../src/assets/softwareSolutions.avif"
export const BgSectionHomeDesk = bg1;
export const BgSectionHomeMob = bg2;
export const ComLogo = logo;
export const menuClosed = menu;
export const menuOpen = cross;
export const HeroSectionImg = img1;
export const HeroSectionRating = img2;
export const HeroSectionVideoWatch = img3;
export const ArrowImg = img4;
export const Whyus1 = img5;
export const Whyus2 = img6;
export const FormBG = bg3;
export const SectionBack = bg4;
export const SectionBack2 = bg5;
export const designSolutions = img7;
export const softwareSolutions = img9;
export const ITSolutions = img8;